[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311', 'py312', 'py313']
include = '\.pyi?$'
exclude = '''
/(
    \.venv
  | venv
  | build
  | dist
  | __pycache__
  | \.git
  | \.mypy_cache
  | \.pytest_cache
  | \.tox
  | \.eggs
  | \.idea
  | \.vscode
  | \.history
  | \.DS_Store
)/
'''
